### ISSUE TITLE
Extension not finding host application

### ISSUE THREAD

**Issue by firestorm517** [bobbyrne01/save-text-to-file-chrome#3]
Installed Python and I've followed the directions exactly as outlines, but the extension still won't find the host application.

My wondering is regards to the registry part. Should "com.my_company.my_application" be something else?

I've checked multiple times and I can't find any fault in my placement of the files or editing them. Of course that doesn't mean there isn't any but I've followed the directions multiple times exactly.

Thanks for any assistance.

**Comment by bobbyrne01** [comment]
Can you share which version of Windows you are on? I can try reproduce, and hopefully provide some instructions

**Comment by firestorm517** [comment]
Hi I replied to your email directly.

Thank you so much for responding.

Kind Regards,
Alan

**Comment by bobbyrne01** [comment]
Unfortunately I didn't receive any email, only your message above. Could you post the info directly on github please?

**Comment by firestorm517** [comment]
Strange it said I could reply to the message directly.

Anyway I'm running the latest build **Windows 10 Version 2004 (19041.264)**

I'll be honest with you though, I did not realize there was no Append feature and it's what I require. I ended up having to just use Auto Hotkey and a script that watches the clipboard for copied text and appends it to my text file.

Will Append be something you can add? Your app would be preferred to the AHK script.

Also I'm pretty sure I followed the directions perfectly but that doesn't mean I did. If I can assist in anyway to figure out if it's my fault or a bug let me know.

Thanks for the Add-on and actually replying!

Regards,
Alan

**Comment by bobbyrne01** [comment]
@firestorm517 I've updated the instructions to install the host application on Windows, would you like to try again? 

The update includes a script which will perform some of the steps automatically for you. 

See: https://github.com/bobbyrne01/save-text-to-file-chrome#step-2-install-host-application

**Comment by bobbyrne01** [comment]
Closing issue, feel free to open a new issue.
