### ISSUE TITLE
Add option to include page title in addition to URL

### ISSUE THREAD

**Issue by jdefgts** [bobbyrne01/save-text-to-file-chrome#5]
This is a very useful tool for research and writing. I appreciate you developing it.

The one improvement I would suggest is that you add the option to include the title of the source page. This would make it helpful in note taking and research applications. 

Thanks for your consideration.

**Comment by bobbyrne01** [comment]
Thanks @jdefgts 

Its worth mentioning, 

> Prefix filename with page title

Is currently an option.

But I guess this request, is a new option, to add the page title into the saved text file too .. which makes sense.

**Comment by jdefgts** [comment]
Thanks for your response. 

My thought was that if you are adding notes about multiple web pages to a single file, it would be helpful to be able to identify the title of the source page. The file name prefix would not preserve that source name.

**Comment by bobbyrne01** [comment]
@jdefgts This is now available in v2.2.1

https://chrome.google.com/webstore/detail/save-text-to-file/mkepenkbhepjelljcfiooignmpfgochi?hl=en

Thanks for the suggestion!
